# Third-party packages: use fully qualified names and trust only the needed item.
tap "rwx-cloud/tap"
brew "rwx-cloud/tap/rwx", trusted: true

# Official Homebrew formulae and casks are trusted automatically.
brew "awscli-local"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "icu4c"
brew "jq"
brew "less"
brew "libpq"
brew "mas"
brew "mise"
brew "neovim"
brew "openssl@3"
brew "overmind"
brew "pkg-config"
brew "postgresql@17"
brew "ripgrep"
brew "stow"
brew "terminal-notifier"
brew "vim"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "cleanshot"
cask "codex"
cask "conductor"
cask "dash"
cask "discord"
cask "figma"
cask "firefox"
cask "ghostty@tip"
cask "google-chrome"
cask "iconjar"
cask "iterm2"
cask "jordanbaird-ice"
cask "linear"
cask "msty"
cask "orbstack"
cask "raycast"
cask "session-manager-plugin"
cask "signal"
cask "slack"
cask "tailscale-app"
cask "visual-studio-code"
cask "zed"
