- homebrew_tap:
    name: neovim/neovim
    state: present

- homebrew:
    update_homebrew: true
    upgrade_all: true

- homebrew:
    name:
      - asdf
      - diff-so-fancy
      - erlang
      - elixir
      - fish
      - fzf
      - gh
      - git
      - gnupg
      - heroku/brew/heroku
      - jq
      - ledger
      - mas
      - neovim
      - openssl
      - pinentry-mac
      - postgresql
      - readline
      - ripgrep
      - sqlite3
      - tmux
      - vim
      - wifi-password
      - xz
      - zlib
    state: latest

- homebrew_cask:
    upgrade_all: true

- homebrew_cask:
    name:
      - 1password
      - alfred
      - bartender
      - google-chrome
      - homebrew/cask/dash
      - homebrew/cask/docker
      - iterm2
      - slack
      - visual-studio-code
    state: upgraded
