- homebrew_tap:
    name: neovim/neovim
    state: present

- homebrew:
    update_homebrew: true
    upgrade_all: true

- homebrew:
    name:
      - asdf
      - diff-so-fancy
      - fish
      - fzf
      - git
      - hub
      - mas
      - neovim
      - openssl
      - postgresql
      - readline
      - reattach-to-user-namespace
      - ripgrep
      - sqlite3
      - tmux
      - vim
      - wifi-password
      - xz
      - zlib
    state: latest

- homebrew_cask:
    upgrade_all: true

- homebrew_cask:
    name:
      - 1password
      - alfred
      - bartender
      - dash
      - docker
      - google-chrome
      - gpg-suite
      - iterm2
      - keybase
      - slack
      - visual-studio-code
    state: upgraded
