- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_presence
  no_log: true

- name: Install Homebrew
  command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
  when: not homebrew_presence.stat.exists

- homebrew_tap:
    name: neovim/neovim
    state: present

- homebrew:
    update_homebrew: true
    upgrade_all: true

- homebrew:
    name:
      - asdf
      - diff-so-fancy
      - fish
      - fzf
      - git
      - hub
      - mas
      - neovim
      - reattach-to-user-namespace
      - ripgrep
      - tmux
      - vim
      - wifi-password
    state: latest

- homebrew_cask:
    upgrade_all: true

- homebrew_cask:
    name:
      - 1password
      - alfred
      - bartender
      - gpg-suite
      - dash
      - google-chrome
      - iterm2
      - slack
      - visual-studio-code
    state: upgraded
