- name: Create temporary rustup installer directory
  tempfile:
    path: "{{ lookup('env', 'HOME') }}"
    state: directory
    suffix: .rustup_install
  register: rustup_installer_directory

- name: Install rustup
  shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y
  args:
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"

- name: Cleanup temporary rustup installer directory
  file:
    path: "{{ rustup_installer_directory.path }}"
    state: absent
