- name: Ensure the .config directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory

- name: Symlink ssh config
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    src: "{{ role_path }}/files/config"
    state: link
    force: true
