- name: Update adsf nodejs
  command: asdf plugin-update nodejs

- name: Check if nodejs is installed
  shell: asdf where nodejs 10.14.0 | grep "not installed"
  register: nodejs_version_check
  ignore_errors: true

- name: Install nodejs
  command: asdf install nodejs 10.14.0
  when: nodejs_version_check.stdout != ""

- name: Set global nodejs version
  command: asdf global nodejs 10.14.0
