- name: Install extensions
  command: code --install-extension {{ item }}
  with_items:
    - Alpha4.jsonl
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - DotJoshJohnson.xml
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - fnando.linter
    - GitHub.copilot
    - GitHub.copilot-chat
    - golang.go
    - hashicorp.hcl
    - hashicorp.terraform
    - hbenl.vscode-test-explorer
    - hbenl.vscode-test-explorer-liveshare
    - kavod-io.vscode-jest-test-adapter
    - mjmcloug.vscode-elixir
    - ms-azuretools.vscode-docker
    - ms-dotnettools.csharp
    - ms-dotnettools.vscode-dotnet-runtime
    - ms-python.debugpy
    - ms-python.isort
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-vscode-remote.remote-containers
    - ms-vscode.test-adapter-converter
    - ms-vscode.vscode-typescript-next
    - ms-vsliveshare.vsliveshare
    - rust-lang.rust-analyzer
    - Shopify.ruby-lsp
    - tomphilbin.gruvbox-themes
    - unifiedjs.vscode-mdx
    - Vue.volar
    - ziyasal.vscode-open-in-github

- name: Remove existing vscode configs
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/{{ item }}"
    state: absent
  with_items:
    - keybindings.json
    - settings.json

- name: Symlink vscode configs
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/{{ item }}"
    src: "{{ role_path }}/files/{{ item }}"
    state: link
    force: true
  with_items:
    - keybindings.json
    - settings.json
