- name: Install extensions
  command: code --install-extension {{ item }}
  with_items:
    - castwide.solargraph
    - connorshea.vscode-ruby-test-adapter
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - hbenl.vscode-test-explorer
    - hbenl.vscode-test-explorer-liveshare
    - kaiwood.endwise
    - kavod-io.vscode-jest-test-adapter
    - misogi.ruby-rubocop
    - mjmcloug.vscode-elixir
    - ms-vscode.test-adapter-converter
    - rebornix.ruby
    - silvenon.mdx
    - tomphilbin.gruvbox-themes
    - ziyasal.vscode-open-in-github

- name: Remove existing vscode configs
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/{{ item }}"
    state: absent
  with_items:
    - keybindings.json
    - settings.json

- name: Symlink vscode configs
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/{{ item }}"
    src: "{{ role_path }}/files/{{ item }}"
    state: link
    force: true
  with_items:
    - keybindings.json
    - settings.json
