- name: Set terraform version
  set_fact:
    tf_version: "0.11.13"

- name: Determine terraform filename
  set_fact:
    tf_binary_download_name: "terraform_{{ tf_version }}_darwin_amd64.zip"

- name: Set terraform urls
  set_fact:
    tf_download_url: "https://releases.hashicorp.com/terraform/{{ tf_version }}/{{ tf_binary_download_name }}"
    tf_sha_sum_url: "https://releases.hashicorp.com/terraform/{{ tf_version }}/terraform_{{ tf_version }}_SHA256SUMS"

- name: Download terraform
  get_url:
    url: "{{ tf_download_url }}"
    dest: ./
    checksum: "sha256:{{ tf_sha_sum_url }}"
  register: terraform_zip_download

- name: Remove any existing terraform version in /usr/local/bin
  file:
    path: /usr/local/bin/terraform
    state: absent

- name: Ensure /usr/local/opt/terraform/bin exists
  file:
    path: /usr/local/opt/terraform/bin
    state: directory
    mode: '0755'

- name: Unpackage terraform binary
  unarchive:
    src: "{{ terraform_zip_download.dest }}"
    dest: /usr/local/opt/terraform/bin
    remote_src: no

- name: Cleanup downloads
  file:
    state: absent
    path: "{{ terraform_zip_download.dest }}"
