- name: Remove existing iterm config
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Preferences/com.googlecode.iterm2.plist"
    state: absent

- name: Symlink iterm config
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Preferences/com.googlecode.iterm2.plist"
    src: "{{ role_path }}/files/com.googlecode.iterm2.plist"
    state: link
    force: true

- name: Symlink hushlogin
  file:
    path: "{{ lookup('env', 'HOME') }}/.hushlogin"
    src: "{{ role_path }}/files/hushlogin"
    state: link
    force: true
